/* idioma.js — dicionário de tradução do painel CRAI.
   Reaproveitável pelo site: expõe T (pt/en), idioma e t(chave, params).
   idioma é lido de localStorage("crai_idioma"); render.js grava ao alternar. */

var T = {
pt:{
  marca_tag:"Recuperação de receita", selo_demo:"Ambiente de demonstração",
  aba_cobrar:"Cobranças", aba_recuperar:"Recuperação", aba_risco:"Clientes em risco",
  aba_mensagens:"Mensagens", aba_visao:"Visão geral",
  cliente:"Cliente", cliente_cobranca:"Cliente", valor_fatura:"Valor da fatura", forma_pagamento:"Forma de pagamento",
  enviar_cobranca:"Enviar cobrança", ver_de_novo:"Ver de novo",

  cobrar_t:"Cobranças", cobrar_s:"Faça uma cobrança de teste e veja o que acontece quando ela é recusada.",
  cobrar_rodape:"Gateway simulado: nenhuma transação real acontece. Na versão em produção, esta tela conversa com o provedor de pagamento contratado.",
  m_pix:"Pix Automático", m_pix_d:"cobrança recorrente autorizada", m_breve:"em breve",
  m_debito:"Cartão de débito", m_debito_d:"em breve", m_boleto:"Boleto", m_boleto_d:"em breve",
  enviando:"Enviando cobrança de {valor} por {metodo}…",
  res_boleto_t:"Boleto emitido", res_boleto_d:"O pagamento pode levar até 3 dias úteis para ser confirmado. A CRAI acompanha e avisa quando cair.",
  res_boleto_r:"Nada a fazer por enquanto.",
  res_falha_t:"Cobrança recusada",
  res_falha_pix:"O cliente não tinha saldo no momento da cobrança.",
  res_falha_d:"{motivo} {cliente} continua devendo {valor}.",
  res_falha_r:"A CRAI já abriu um caso de recuperação para este cliente.",
  res_falha_b:"Ver o que a CRAI vai fazer",

  recup_t:"Recuperação", recup_s:"Mexa nos controles e veja a decisão mudar. Nada aqui é roteiro: cada número é recalculado a partir do que você escolhe.",
  recup_rodape:"A decisão, o score, o e-Profit, a explicação e o plano de tentativas vêm da API da CRAI, com os modelos treinados. Esta tela só exibe — ela não calcula nada.",
  rec_vazio_t:"Aguardando uma cobrança",
  rec_vazio_d:"A CRAI reage a eventos: ela só entra em ação quando uma cobrança é recusada. Vá até a aba Cobranças e dispare uma — o caso chega aqui.",
  rec_ir_cobrar:"Ir para Cobranças", rec_recomecar:"Começar de novo",
  rec_sabe_t:"O que o sistema já sabe", rec_sabe_d:"Nada aqui foi digitado por você. A CRAI lê do histórico de pagamentos e do comportamento do cliente.",
  rec_qual_caso:"Cobrança em análise",
  f_hist:"Histórico de pagamento", f_hist_de:"últimos 12 meses de faturas deste cliente",
  f_falhas:"Falhas nos últimos 90 dias", f_falhas_de:"contadas no histórico de cobrança",
  f_perfil:"Perfil de pagador", f_perfil_de:"detectado pelo padrão de entrada de dinheiro",
  f_valor:"Valor da fatura", f_valor_de:"da cobrança que foi recusada",
  f_cliente:"Cliente", f_cliente_de:"identifica o perfil de pagador consultado",
  f_causa:"Causa da recusa", f_causa_de:"informada pelo Pix Automático",
  cz_saldo:"Sem saldo na conta", cz_autorizacao:"Autorização cancelada", cz_conta:"Dados da conta inválidos",
  p3_na_autorizacao:"O cliente cancelou a autorização do Pix Automático. Tentar de novo não resolve — ele precisa autorizar outra vez.",
  p3_na_conta:"Os dados bancários não conferem. Tentar de novo não resolve — o cliente precisa corrigir o cadastro.",
  ver_mensagem:"Ver a mensagem", p5_curto:"A CRAI já preparou o que dizer a este cliente.",
  rec_msg_h:"Três formas de avisar", rec_msg_s:"A CRAI monta as três e recomenda a de maior chance de resposta para este cliente.",
  recomendada:"Recomendada pelo sistema", chance_resposta:"{p}% de chance de resposta",
  rv_calma:"Tranquila", rv_direta:"Direta", rv_prazo:"Com prazo",
  saldo_calma:"Oi! Sua fatura de {valor} não passou por falta de saldo. Já reagendamos a cobrança para {data} — não precisa fazer nada.",
  saldo_direta:"Oi! A cobrança de {valor} não passou. Vamos tentar de novo em {data}. Se preferir acertar agora, é só tocar aqui.",
  saldo_prazo:"Oi! Sua assinatura está com uma fatura de {valor} em aberto. A nova tentativa é em {data}; depois disso o acesso pode ficar suspenso.",
  autoriz_calma:"Oi! O Pix Automático da sua assinatura foi cancelado, por isso a fatura de {valor} não passou. Autorize de novo quando puder.",
  autoriz_direta:"Oi! Sua assinatura parou de cobrar porque o Pix Automático foi cancelado. Autorize de novo aqui — leva menos de um minuto.",
  autoriz_prazo:"Oi! Sem a autorização do Pix Automático não conseguimos renovar sua assinatura de {valor}. Reautorize por aqui para não perder o acesso.",
  conta_calma:"Oi! Não conseguimos cobrar porque os dados bancários estão desatualizados. Atualize quando puder e a gente segue.",
  conta_direta:"Oi! Os dados bancários da sua assinatura não conferem mais. Atualize aqui e a cobrança de {valor} volta ao normal.",
  conta_prazo:"Oi! A fatura de {valor} não pôde ser cobrada: dados bancários inválidos. Atualize por aqui para manter o acesso ativo.",
  msg_do_caso:"Cliente do caso de recuperação", msg_voltar:"Voltar para a Recuperação",
  dec_score:"Chance baixa demais", dec_score_d:"A chance de recuperar ficou abaixo do mínimo que justifica agir. A CRAI encerra o caso em vez de incomodar o cliente por nada.",
  pf_clt:"CLT", pf_pj:"PJ", pf_free:"Autônomo",
  big_chance:"Chance de recuperar", big_chance_pe:"neste momento, com estes dados",
  big_retorno:"Retorno esperado", big_retorno_pe:"chance × valor − custo",
  big_custo:"Custo acumulado", big_custo_pe:"{n} tentativa(s) até aqui",
  dec_sim:"Vale tentar de novo", dec_sim_d:"O retorno esperado supera o custo. A CRAI segue com o caso sozinha.",
  dec_nao:"Não vale tentar", dec_nao_d:"O custo de insistir supera o que se espera recuperar. A CRAI encerra o caso em vez de gastar o seu dinheiro.",
  p1_t:"Evento recebido", p1_d:"{cliente} — fatura de {valor} recusada.",
  p2_t:"Diagnóstico", p2_d:"O que pesa a favor e contra a recuperação deste caso.",
  ct_causa:"Causa da recusa", ct_historico:"Histórico de pagamento", ct_falhas:"Falhas recentes",
  ct_valor:"Valor da fatura", ct_tentativa:"Número da tentativa",
  p3_t:"Plano de cobrança", p3_d:"Quando tentar de novo, segundo o padrão de dinheiro em conta deste perfil.",
  p3_na:"Retentativa não se aplica",
  tentativa_n:"Tentativa {n}", prevista:"prevista para {data}", margem:"margem de {m} dia",
  p4_t:"Execução", p4_d:"Rode o plano e acompanhe o que acontece a cada tentativa.",
  executar:"Executar o plano", executando:"Executando…", exec_refeito:"Rodar de novo",
  t_pendente:"aguardando", t_falhou:"não passou", t_pagou:"pago",
  p5_t:"Mensagem ao cliente", p5_d:"Enviada pelo canal com maior chance de resposta, sem pedir que ele fale com ninguém.",
  fim_ok:"Recuperado em {n} tentativa(s)", fim_ok_d:"{valor} de volta, sem ninguém da sua equipe tocar no caso.",
  fim_nao:"As três tentativas falharam", fim_nao_d:"O dinheiro não entrou em nenhuma das janelas previstas. A CRAI para de cobrar sozinha aqui e passa a falar com o cliente — a mensagem abaixo é o próximo passo.",
  fim_desistiu:"Encerrado por não valer a pena", fim_desistiu_d:"O retorno esperado ficou abaixo do custo. Insistir gastaria mais do que traria de volta.",
  reais:"R$",

  risco_t:"Clientes em risco", risco_s:"Envie a sua base de clientes e descubra quem está prestes a cancelar — antes que cancele.",
  risco_rodape:"A planilha é enviada para a API da CRAI e a análise roda no servidor, com a régua tirada da sua própria base. Em ambiente de demonstração os dados ficam num banco local.",
  solta_t:"Arraste a planilha aqui, ou clique para escolher", solta_d:"Aceita CSV com a lista de clientes da sua empresa",
  ou_exemplo:"Ou use uma base de exemplo",
  ex_diaria:"Empresa de uso diário", ex_diaria_d:"240 clientes que entram quase todo dia",
  ex_mensal:"Empresa de uso mensal", ex_mensal_d:"180 clientes que entram uma vez por mês",
  ex_saudavel:"Base saudável", ex_saudavel_d:"120 clientes, todos ativos",
  an1:"Lendo a base…", an1s:"{n} clientes encontrados",
  an2:"Descobrindo o ritmo da sua empresa…", an2s:"cada base tem um padrão de uso diferente",
  an3:"Comparando cada cliente com os outros…", an3s:"quem está fora do ritmo da própria base",
  an4:"Pronto", an4s:"organizando o resultado",
  n_critico:"Risco alto", n_alto:"Atenção", n_normal:"Tudo certo", n_semdado:"Sem dados",
  d_criticos:"Risco alto", d_criticos_pe:"precisam de ação agora",
  d_altos:"Atenção", d_altos_pe:"vale acompanhar de perto",
  d_receita:"Receita protegida se agir", d_receita_pe:"por mês, somando os dois grupos",
  g_dist_t:"Como sua base está distribuída", g_dist_s:"{n} clientes de {rotulo}.",
  g_ritmo_t:"O ritmo da sua base",
  g_ritmo_s:"Foi isso que a CRAI aprendeu sobre como seus clientes usam o produto.",
  g_ritmo_s2:"Base pequena demais para tirar um padrão — usamos a referência geral.",
  r_mediana:"A maioria entra a cada", r_p75:"Começa a preocupar a partir de", r_p90:"Os mais sumidos passam de",
  dia:"dia", dias:"dias",
  lista_t:"Quem precisa de atenção", lista_s:"Do mais urgente para o menos urgente.",
  outra_base:"Usar outra base",
  vazio_t:"Ninguém em risco nesta base",
  vazio_d:"Alguém sempre é o último da fila — mas aqui ninguém está realmente sumido. A CRAI não inventa problema para se justificar.",
  expl_p90:"Sem entrar há {dias} dias — mais do que 90% dos seus clientes.",
  expl_p75:"Sem entrar há {dias} dias, quando a maioria entra a cada {mediana}.",
  expl_normal:"Dentro do ritmo normal da sua base.",
  expl_fim_fila:"Está no fim da fila, mas {dias} dias é normal nesta base.",
  expl_semdado:"Sem sinal de atividade no período.",
  expl_pequena:"Base pequena demais para comparação — avaliado pela régua padrão.",
  erro_csv_t:"Não deu para ler essa planilha",
  erro_csv_d:"Encontramos as colunas: <b>{cols}</b>.<br>Precisamos de pelo menos uma coluna com os dias sem acesso (ou a data do último acesso) e, de preferência, quantas funcionalidades cada cliente usa.",

  msg_t:"Mensagens", msg_s:"Escolha um cliente para ver o que a CRAI diria — ou deixe que ela decida e fale com todos que precisam.",
  msg_rodape:"Envio simulado nesta fase. O texto mostrado é o que sairia pelo canal escolhido.",
  modo_um:"Escolher um cliente", modo_todos:"A CRAI decide e envia para todos",
  tres_formas:"Três formas de falar com ele", escolhida:"Escolhida",
  chance_dar_certo:"{p}% de chance de dar certo",
  v_leve:"Leve", v_direto:"Direto", v_valor:"Valor",
  v_leve_txt:"Oi, {nome}! Vimos que você não passou por aqui esta semana. Tem algo em que a gente possa ajudar?",
  v_direto_txt:"Seu plano renova em 6 dias e você usou só {feats} dos recursos disponíveis. Quer 2 meses com 30% para dar uma segunda chance?",
  v_valor_txt:"Empresas parecidas com a sua economizam 4 horas por semana com o módulo de conciliação. Deixamos liberado por 30 dias?",
  of_sem:"Sem oferta", of_desc:"30% por 2 meses", of_extra:"Recurso extra liberado",
  por_onde:"Por onde falar", por_onde_s:"A CRAI escolhe o canal com mais chance de resposta para este cliente.",
  c_whats:"WhatsApp", c_whats_d:"tem telefone e costuma responder",
  c_popup:"Aviso no produto", c_popup_d:"ele não está entrando no sistema",
  c_email:"E-mail", c_email_d:"abre poucos e-mails nossos",
  escolhido:"Escolhido", descartado:"Descartado",
  enviar_msg:"Enviar mensagem", envio_simulado:"Envio simulado nesta demonstração.",
  msg_enviada_t:"Mensagem enviada",
  msg_enviada_d:"WhatsApp · agora mesmo. Se ele responder, a CRAI aprende com o resultado e melhora a próxima escolha.",
  lote_t:"Enviar para todos que precisam",
  lote_s:"A CRAI escolhe a melhor mensagem e o melhor canal para cada cliente, um por um.",
  lote_fila:"Clientes na fila", lote_fila_pe:"com risco alto ou atenção",
  lote_receita:"Receita envolvida", lote_receita_pe:"por mês",
  lote_btn:"Deixar a CRAI cuidar disso", lote_enviando:"Enviando…", lote_pronto:"Pronto",
  lote_fim_t:"{n} clientes contatados",
  lote_fim_d:"Cada um recebeu a mensagem com mais chance de funcionar, pelo canal com mais chance de resposta. Os resultados aparecem na Visão geral.",
  tom_leve:"tom leve", tom_direto:"tom direto", tom_valor:"tom de valor",
  enviado_por:"{tom} · enviado por {canal}", por_mes:"{v}/mês",
  msg_sem_base_t:"Analise uma base primeiro",
  msg_sem_base_d:"As mensagens são montadas para clientes reais da sua base. Envie a sua planilha na aba Clientes em risco.",
  ir_risco:"Ir para Clientes em risco",

  visao_t:"Visão geral", visao_s:"O resumo do que a CRAI recupera para você — montado a partir das análises que você fez nas outras abas.",
  visao_vazio_t:"Ainda não há nada para resumir",
  visao_vazio_d:"Esta aba não inventa número: tudo o que ela mostra vem das outras abas. Comece enviando a sua base de clientes.",
  proj_data:"Projetar até", proj_ate:"Até {data}",
  at_3m:"3 meses", at_6m:"6 meses", at_12m:"12 meses",
  vg_mrr_risco:"MRR em risco hoje", vg_mrr_risco_pe:"{n} clientes com sinal de saída",
  vg_mrr_salvo:"MRR que a CRAI salva por mês", vg_mrr_salvo_pe:"{pct}% do que está em risco",
  vg_ganho:"Receita acumulada até {data}", vg_ganho_pe:"{meses} meses de MRR salvo + faturas recuperadas",
  g_proj_t:"Quanto você ganha ao longo do tempo", g_proj_s:"Receita acumulada, mês a mês, a partir da sua base.",
  g_proj_alt:"Gráfico de receita acumulada mês a mês até a data escolhida.",
  origem_t:"De onde vem cada número", origem_s:"Nenhum valor desta aba é inventado.",
  o_base:"Base analisada", o_base_de:"aba Clientes em risco",
  o_risco:"Clientes em risco", o_risco_de:"alto risco + atenção, da análise da sua base",
  o_mrr:"MRR desses clientes", o_mrr_de:"soma do valor mensal de cada um",
  o_taxa:"Taxa de aceite da oferta", o_taxa_de:"aba Mensagens, oferta escolhida pelo sistema",
  o_cobr:"Cobranças recusadas", o_cobr_de:"aba Cobranças",
  o_recup:"Faturas recuperadas", o_recup_de:"aba Recuperação",
  o_contatados:"Clientes contatados", o_contatados_de:"aba Mensagens",
  nenhum:"nenhum", nenhuma:"nenhuma",
  formula_t:"Como a projeção é calculada",
  formula_d:"MRR salvo por mês = soma do valor mensal dos clientes em risco × taxa de aceite da oferta escolhida. A receita acumulada multiplica isso pelos meses até a data, e soma as faturas já recuperadas. É projeção, não promessa.",
  mes:"mês", meses:"meses",
  /* ── estados de erro ─────────────────────────────────────────── */
  erro_tempo_t:"A resposta demorou demais",
  erro_tempo_d:"O servidor não respondeu em {s} segundos. Nada foi exibido: a tela prefere não mostrar nada a mostrar dado velho.",
  erro_http_t:"O servidor recusou o pedido",
  erro_http_d:"Resposta {status} em {rota}.",
  erro_resposta_t:"Resposta fora do formato esperado",
  erro_resposta_d:"A rota {rota} devolveu algo que esta tela não sabe ler. Nada foi exibido.",
  erro_modelos_t:"Modelos não carregados no servidor",
  erro_modelos_d:"A API está no ar, mas os modelos treinados não estão em disco. A análise não roda assim, e a tela não inventa número no lugar.",
  erro_importacao_t:"Nada foi importado",
  erro_importacao_d:"Nenhuma linha da planilha foi aceita. O motivo veio da API e está abaixo.",
  erro_rede_t:"Sem resposta do servidor",
  erro_rede_d:"Não foi possível falar com a API. Confira se ela está no ar e tente de novo.",
  tentar_de_novo:"Tentar de novo",

  /* ── importação e régua da base ──────────────────────────────── */
  r_colunas_faltando:"Colunas não encontradas",
  linha_n:"Linha {n}: {motivo}",
  e_mais:"e mais {n}",
  g_regua_t:"De onde saiu o corte",
  g_regua_s:"A CRAI não usa um limite fixo para todo mundo. Ela mede a distribuição da sua base e tira o corte dela.",
  r_regua_base:"Corte tirado da sua base",
  r_regua_padrao:"Corte padrão",
  n_clientes:"{n} clientes",
  r_importados:"Clientes importados",
  r_rejeitados:"Linhas rejeitadas",
  r_sem_dado:"Linhas sem dado de uso",
  r_gerado_em:"Análise feita em",
  regua_padrao_aviso:"Base pequena demais para tirar o corte dela. Nesses casos a CRAI usou o corte padrão, e avisa em vez de esconder.",

  /* ── lista de clientes em risco ──────────────────────────────── */
  buscar_cliente:"Buscar cliente pelo código",
  busca_vazia:"Nenhum cliente com esse código",
  semdado_t:"{n} clientes sem dado de atividade",
  semdado_d:"Faltou informação de uso para esses clientes. A CRAI não atribui risco a quem ela não consegue medir, e por isso eles aparecem com travessão em vez de zero.",

  /* ── cobrança ────────────────────────────────────────────────── */
  valor_invalido_t:"Valor inválido",
  valor_invalido_d:"Escreva um valor como 489,00.",

  /* ── recuperação ─────────────────────────────────────────────── */
  caso_n:"Caso {n}",
  f_tentativas:"Tentativas já usadas",
  f_tentativas_de:"das 3 permitidas na janela de 7 dias do Pix Automático",
  f_lido_de:"lido pela CRAI do histórico deste cliente",
  f_nao_devolvido:"não devolvido pela API nesta resposta",
  p2_sem_shap:"A API não devolveu a explicação desta decisão.",
  p_racio_d:"O caminho que o agente percorreu até decidir.",
  p_racio_vazio:"A API não devolveu o raciocínio desta decisão.",
  p3_sem_plano:"Não há retentativa a agendar: {decisao}.",
  melhor_eprofit:"maior retorno",
  canal_humano:"canal humano",
  canal_nota:"A mensagem sai por {escolhido} porque é o único canal com integração de envio nesta fase. O maior retorno do comparativo seria {melhor}.",
  p_canal_d:"Cada canal tem um custo e uma chance de resposta. A CRAI compara o retorno de todos antes de escolher.",
  p_canal_vazio:"A API não devolveu o comparativo de canal.",
  p5_d_api:"Enviada por {canal}, sem pedir que o cliente fale com ninguém.",
  p5_sem_msg:"A API não devolveu mensagem para este caso.",

  /* ── mensagens ───────────────────────────────────────────────── */
  msg_ninguem_t:"Ninguém em risco nesta base",
  msg_ninguem_d:"A análise não encontrou cliente em risco alto ou crítico. Não há mensagem a preparar, e isso é resultado, não falha.",
  origem_gerado:"texto gerado pela Claude API",
  origem_template:"texto de modelo pronto",
  escolhida_bandit:"escolhida",
  aceite_aprendido:"{p} de aceite aprendido",
  retorno_esperado:"retorno esperado {v}",
  posterior_linha:"Os {p} vêm da distribuição que a CRAI mantém para esta oferta neste cliente-empresa: {a} aceites contra {b} recusas, peso total {peso}, já incluída a estimativa inicial de mercado. Cada desfecho real move esse número.",
  decisao_resumo:"Oferta escolhida: {oferta}. Risco {risco}, valor mensal {mrr}.",
  envio_simulado_t:"Envio simulado",
  envio_registrado:"Ciclo registrado sob {id}.",
  envio_nao_registrado:"Nenhum ciclo foi registrado por este disparo.",
  um_fora_do_lote:"Este cliente já entrou no disparo em lote. Decidir de novo roda o lote outra vez.",
  um_explica:"Rodar a decisão deste cliente dispara o lote inteiro, porque a régua da base precisa de todos para funcionar.",
  decidir_um:"Ver a decisão deste cliente",
  lote_de_novo:"Disparar de novo",
  lote_tratados:"Clientes tratados",
  lote_tratados_pe:"{mrr} de valor mensal envolvido",
  lote_pulados:"Clientes pulados",
  lote_pulados_pe:"de {n} recebidos",
  lote_por_canal:"Por canal",
  lote_lista_t:"Os {n} clientes tratados",
  ver_decisao:"Ver decisão",
  lote_ninguem_t:"Ninguém foi abordado neste lote",
  lote_ninguem_d:"Nenhum cliente desta base passou no critério de e-Profit. A CRAI não fala com quem não compensa abordar.",
  lote_pulados_t:"Por que {n} foram pulados",
  pulado_abaixo_do_criterio:"Abaixo do critério de retorno",
  pulado_dado_insuficiente:"Sem dado de atividade suficiente",
  pulado_ciclo_aberto:"Já contatado, aguardando resposta",
  pulado_cadastro_invalido:"Cadastro inválido na planilha",

  /* ── visão geral ─────────────────────────────────────────────── */
  vg_sem_taxa:"nenhum disparo ainda",
  vg_sem_taxa_t:"Ainda falta a taxa de aceite",
  vg_sem_taxa_d:"A projeção precisa da taxa de aceite da oferta escolhida, e ela vem da aba Mensagens. Dispare um lote e o gráfico aparece.",
  p_racio_t:"Como o agente decidiu",
  p_canal_t:"Por onde falar com o cliente",
  ci_bot_whatsapp:"Bot de WhatsApp",
  ci_email_auto:"E-mail automático",
  ci_sms:"SMS",
  ci_ligacao_cs:"Ligação do atendimento",
  ci_pix_boleto_link:"Link de Pix ou boleto"
},
en:{
  marca_tag:"Revenue recovery", selo_demo:"Demo environment",
  aba_cobrar:"Charges", aba_recuperar:"Recovery", aba_risco:"At-risk customers",
  aba_mensagens:"Messages", aba_visao:"Overview",
  cliente:"Customer", cliente_cobranca:"Customer", valor_fatura:"Invoice amount", forma_pagamento:"Payment method",
  enviar_cobranca:"Send charge", ver_de_novo:"Play again",

  cobrar_t:"Charges", cobrar_s:"Run a test charge and see what happens when it is declined.",
  cobrar_rodape:"Simulated gateway: no real transaction happens. In production, this screen talks to your payment provider.",
  m_pix:"Pix Automático", m_pix_d:"authorised recurring charge", m_breve:"coming soon",
  m_debito:"Debit card", m_debito_d:"coming soon", m_boleto:"Boleto", m_boleto_d:"coming soon",
  enviando:"Sending a {valor} charge via {metodo}…",
  res_boleto_t:"Boleto issued", res_boleto_d:"Payment may take up to 3 business days to clear. CRAI watches it and tells you when it lands.",
  res_boleto_r:"Nothing to do for now.",
  res_falha_t:"Charge declined",
  res_falha_pix:"The customer had no balance at the time of the charge.",
  res_falha_d:"{motivo} {cliente} still owes {valor}.",
  res_falha_r:"CRAI has already opened a recovery case for this customer.",
  res_falha_b:"See what CRAI will do",

  recup_t:"Recovery", recup_s:"Move the controls and watch the decision change. Nothing here is scripted: every number is recomputed from what you choose.",
  recup_rodape:"The decision, the score, the e-Profit, the explanation and the retry plan all come from the CRAI API, with the trained models. This screen only displays — it computes nothing.",
  rec_vazio_t:"Waiting for a charge",
  rec_vazio_d:"CRAI reacts to events: it only steps in when a charge is declined. Go to the Charges tab and run one — the case lands here.",
  rec_ir_cobrar:"Go to Charges", rec_recomecar:"Start over",
  rec_sabe_t:"What the system already knows", rec_sabe_d:"Nothing here was typed by you. CRAI reads it from the payment history and the customer's behaviour.",
  rec_qual_caso:"Charge under analysis",
  f_hist:"Payment history", f_hist_de:"last 12 months of this customer's invoices",
  f_falhas:"Failures in the last 90 days", f_falhas_de:"counted in the billing history",
  f_perfil:"Payer profile", f_perfil_de:"detected from the cash-in pattern",
  f_valor:"Invoice amount", f_valor_de:"from the charge that was declined",
  f_cliente:"Customer", f_cliente_de:"identifies the payer profile that was looked up",
  f_causa:"Decline reason", f_causa_de:"reported by Pix Automático",
  cz_saldo:"No balance in account", cz_autorizacao:"Authorisation cancelled", cz_conta:"Invalid account details",
  p3_na_autorizacao:"The customer cancelled the Pix Automático authorisation. Retrying does not fix it — they have to authorise again.",
  p3_na_conta:"The bank details do not match. Retrying does not fix it — the customer has to correct the record.",
  ver_mensagem:"See the message", p5_curto:"CRAI has already prepared what to say to this customer.",
  rec_msg_h:"Three ways to let them know", rec_msg_s:"CRAI drafts all three and recommends the one most likely to get a reply from this customer.",
  recomendada:"Recommended by the system", chance_resposta:"{p}% chance of a reply",
  rv_calma:"Calm", rv_direta:"Direct", rv_prazo:"With a deadline",
  saldo_calma:"Hi! Your {valor} invoice didn't go through — no balance. We've already rescheduled the charge for {data}, nothing for you to do.",
  saldo_direta:"Hi! The {valor} charge didn't go through. We'll try again on {data}. If you'd rather settle now, just tap here.",
  saldo_prazo:"Hi! Your subscription has a {valor} invoice open. The next attempt is on {data}; after that your access may be suspended.",
  autoriz_calma:"Hi! The Pix Automático on your subscription was cancelled, so the {valor} invoice didn't go through. Authorise it again whenever you can.",
  autoriz_direta:"Hi! Your subscription stopped charging because Pix Automático was cancelled. Authorise it again here — takes under a minute.",
  autoriz_prazo:"Hi! Without the Pix Automático authorisation we can't renew your {valor} subscription. Re-authorise here so you don't lose access.",
  conta_calma:"Hi! We couldn't charge you because the bank details are out of date. Update them whenever you can and we'll carry on.",
  conta_direta:"Hi! Your subscription's bank details no longer match. Update them here and the {valor} charge goes back to normal.",
  conta_prazo:"Hi! The {valor} invoice couldn't be charged: invalid bank details. Update them here to keep your access active.",
  msg_do_caso:"Customer from the recovery case", msg_voltar:"Back to Recovery",
  dec_score:"Chance too low", dec_score_d:"The chance of recovery fell below the minimum that justifies acting. CRAI closes the case instead of bothering the customer for nothing.",
  pf_clt:"Salaried", pf_pj:"Company", pf_free:"Freelancer",
  big_chance:"Chance of recovery", big_chance_pe:"right now, with these inputs",
  big_retorno:"Expected return", big_retorno_pe:"chance × amount − cost",
  big_custo:"Accumulated cost", big_custo_pe:"{n} attempt(s) so far",
  dec_sim:"Worth trying again", dec_sim_d:"The expected return beats the cost. CRAI carries on with the case on its own.",
  dec_nao:"Not worth trying", dec_nao_d:"Pushing costs more than what we expect to recover. CRAI closes the case instead of spending your money.",
  p1_t:"Event received", p1_d:"{cliente} — {valor} invoice declined.",
  p2_t:"Diagnosis", p2_d:"What weighs for and against recovering this case.",
  ct_causa:"Decline reason", ct_historico:"Payment history", ct_falhas:"Recent failures",
  ct_valor:"Invoice amount", ct_tentativa:"Attempt number",
  p3_t:"Collection plan", p3_d:"When to try again, based on this profile's cash-in-account pattern.",
  p3_na:"Retry does not apply",
  tentativa_n:"Attempt {n}", prevista:"scheduled for {data}", margem:"margin of {m} day",
  p4_t:"Execution", p4_d:"Run the plan and follow what happens on each attempt.",
  executar:"Run the plan", executando:"Running…", exec_refeito:"Run again",
  t_pendente:"waiting", t_falhou:"declined", t_pagou:"paid",
  p5_t:"Message to the customer", p5_d:"Sent through the channel most likely to get a reply, without asking them to talk to anyone.",
  fim_ok:"Recovered in {n} attempt(s)", fim_ok_d:"{valor} back, without anyone on your team touching the case.",
  fim_nao:"All three attempts failed", fim_nao_d:"The money did not arrive in any of the predicted windows. CRAI stops charging on its own here and starts talking to the customer — the message below is the next step.",
  fim_desistiu:"Closed as not worth it", fim_desistiu_d:"The expected return fell below the cost. Pushing would spend more than it would bring back.",
  reais:"R$",

  risco_t:"At-risk customers", risco_s:"Upload your customer base and find out who is about to cancel — before they do.",
  risco_rodape:"The spreadsheet is sent to the CRAI API and the analysis runs on the server, with the thresholds taken from your own base. In the demo environment the data stays in a local database.",
  solta_t:"Drop your spreadsheet here, or click to choose", solta_d:"Accepts a CSV with your company's customer list",
  ou_exemplo:"Or use a sample base",
  ex_diaria:"Daily-use company", ex_diaria_d:"240 customers who log in almost every day",
  ex_mensal:"Monthly-use company", ex_mensal_d:"180 customers who log in once a month",
  ex_saudavel:"Healthy base", ex_saudavel_d:"120 customers, all active",
  an1:"Reading the base…", an1s:"{n} customers found",
  an2:"Learning your company's rhythm…", an2s:"every base has a different usage pattern",
  an3:"Comparing each customer with the others…", an3s:"who is out of step with their own base",
  an4:"Done", an4s:"organising the result",
  n_critico:"High risk", n_alto:"Watch", n_normal:"All good", n_semdado:"No data",
  d_criticos:"High risk", d_criticos_pe:"need action now",
  d_altos:"Watch", d_altos_pe:"worth keeping an eye on",
  d_receita:"Revenue protected if you act", d_receita_pe:"per month, both groups combined",
  g_dist_t:"How your base is distributed", g_dist_s:"{n} customers from {rotulo}.",
  g_ritmo_t:"Your base's rhythm",
  g_ritmo_s:"This is what CRAI learned about how your customers use the product.",
  g_ritmo_s2:"Base too small to derive a pattern — using the general reference.",
  r_mediana:"Most log in every", r_p75:"Starts to worry past", r_p90:"The quietest go beyond",
  dia:"day", dias:"days",
  lista_t:"Who needs attention", lista_s:"Most urgent first.",
  outra_base:"Use another base",
  vazio_t:"Nobody at risk in this base",
  vazio_d:"Someone is always last in line — but nobody here has really gone quiet. CRAI does not invent a problem to justify itself.",
  expl_p90:"No login for {dias} days — more than 90% of your customers.",
  expl_p75:"No login for {dias} days, when most log in every {mediana}.",
  expl_normal:"Within your base's normal rhythm.",
  expl_fim_fila:"Last in line, but {dias} days is normal in this base.",
  expl_semdado:"No activity signal in the period.",
  expl_pequena:"Base too small to compare — scored with the standard ruler.",
  erro_csv_t:"Could not read that spreadsheet",
  erro_csv_d:"We found these columns: <b>{cols}</b>.<br>We need at least a column with days since last access (or the last access date) and, ideally, how many features each customer uses.",

  msg_t:"Messages", msg_s:"Pick a customer to see what CRAI would say — or let it decide and reach everyone who needs it.",
  msg_rodape:"Sending is simulated at this stage. The text shown is what would go out through the chosen channel.",
  modo_um:"Pick one customer", modo_todos:"CRAI decides and sends to everyone",
  tres_formas:"Three ways to reach them", escolhida:"Chosen",
  chance_dar_certo:"{p}% chance of working",
  v_leve:"Light", v_direto:"Direct", v_valor:"Value",
  v_leve_txt:"Hi, {nome}! We noticed you haven't been around this week. Anything we can help unblock?",
  v_direto_txt:"Your plan renews in 6 days and you've used only {feats} of the available features. Want 2 months at 30% off to give it another go?",
  v_valor_txt:"Companies like yours save 4 hours a week with the reconciliation module. Shall we unlock it for 30 days?",
  of_sem:"No offer", of_desc:"30% for 2 months", of_extra:"Extra feature unlocked",
  por_onde:"Where to reach them", por_onde_s:"CRAI picks the channel most likely to get a reply from this customer.",
  c_whats:"WhatsApp", c_whats_d:"has a phone and usually replies",
  c_popup:"In-product notice", c_popup_d:"they are not logging in",
  c_email:"Email", c_email_d:"rarely opens our emails",
  escolhido:"Chosen", descartado:"Discarded",
  enviar_msg:"Send message", envio_simulado:"Sending is simulated in this demo.",
  msg_enviada_t:"Message sent",
  msg_enviada_d:"WhatsApp · just now. If they reply, CRAI learns from the outcome and improves the next choice.",
  lote_t:"Send to everyone who needs it",
  lote_s:"CRAI picks the best message and the best channel for each customer, one by one.",
  lote_fila:"Customers in queue", lote_fila_pe:"at high risk or watch",
  lote_receita:"Revenue involved", lote_receita_pe:"per month",
  lote_btn:"Let CRAI handle it", lote_enviando:"Sending…", lote_pronto:"Done",
  lote_fim_t:"{n} customers contacted",
  lote_fim_d:"Each got the message most likely to work, through the channel most likely to get a reply. Results show up in the Overview.",
  tom_leve:"light tone", tom_direto:"direct tone", tom_valor:"value tone",
  enviado_por:"{tom} · sent via {canal}", por_mes:"{v}/mo",
  msg_sem_base_t:"Analyse a base first",
  msg_sem_base_d:"Messages are built for real customers from your base. Upload your spreadsheet in the At-risk customers tab.",
  ir_risco:"Go to At-risk customers",

  visao_t:"Overview", visao_s:"A summary of what CRAI recovers for you — built from the analyses you ran in the other tabs.",
  visao_vazio_t:"Nothing to summarise yet",
  visao_vazio_d:"This tab invents no numbers: everything it shows comes from the other tabs. Start by uploading your customer base.",
  proj_data:"Project until", proj_ate:"Until {data}",
  at_3m:"3 months", at_6m:"6 months", at_12m:"12 months",
  vg_mrr_risco:"MRR at risk today", vg_mrr_risco_pe:"{n} customers showing exit signals",
  vg_mrr_salvo:"MRR CRAI saves per month", vg_mrr_salvo_pe:"{pct}% of what is at risk",
  vg_ganho:"Cumulative revenue by {data}", vg_ganho_pe:"{meses} months of saved MRR + recovered invoices",
  g_proj_t:"What you gain over time", g_proj_s:"Cumulative revenue, month by month, from your own base.",
  g_proj_alt:"Cumulative revenue chart, month by month, up to the chosen date.",
  origem_t:"Where each number comes from", origem_s:"No value on this tab is invented.",
  o_base:"Base analysed", o_base_de:"At-risk customers tab",
  o_risco:"Customers at risk", o_risco_de:"high risk + watch, from your base analysis",
  o_mrr:"MRR of those customers", o_mrr_de:"sum of each one's monthly value",
  o_taxa:"Offer acceptance rate", o_taxa_de:"Messages tab, offer chosen by the system",
  o_cobr:"Declined charges", o_cobr_de:"Charges tab",
  o_recup:"Invoices recovered", o_recup_de:"Recovery tab",
  o_contatados:"Customers contacted", o_contatados_de:"Messages tab",
  nenhum:"none", nenhuma:"none",
  formula_t:"How the projection is calculated",
  formula_d:"Saved MRR per month = sum of the monthly value of at-risk customers × the acceptance rate of the chosen offer. Cumulative revenue multiplies that by the months until the date and adds the invoices already recovered. It is a projection, not a promise.",
  mes:"month", meses:"months",
  /* ── error states ────────────────────────────────────────────── */
  erro_tempo_t:"The response took too long",
  erro_tempo_d:"The server did not answer within {s} seconds. Nothing was shown: this screen would rather show nothing than stale data.",
  erro_http_t:"The server refused the request",
  erro_http_d:"Status {status} from {rota}.",
  erro_resposta_t:"Response in an unexpected shape",
  erro_resposta_d:"The route {rota} returned something this screen cannot read. Nothing was shown.",
  erro_modelos_t:"Models not loaded on the server",
  erro_modelos_d:"The API is up, but the trained models are not on disk. The analysis cannot run, and this screen will not invent a number in their place.",
  erro_importacao_t:"Nothing was imported",
  erro_importacao_d:"No row from the spreadsheet was accepted. The reason came from the API and is shown below.",
  erro_rede_t:"No answer from the server",
  erro_rede_d:"Could not reach the API. Check whether it is running and try again.",
  tentar_de_novo:"Try again",

  /* ── import and base thresholds ──────────────────────────────── */
  r_colunas_faltando:"Columns not found",
  linha_n:"Row {n}: {motivo}",
  e_mais:"and {n} more",
  g_regua_t:"Where the threshold came from",
  g_regua_s:"CRAI does not use one fixed limit for everyone. It measures how your base is distributed and derives the cut from it.",
  r_regua_base:"Threshold from your base",
  r_regua_padrao:"Default threshold",
  n_clientes:"{n} customers",
  r_importados:"Customers imported",
  r_rejeitados:"Rows rejected",
  r_sem_dado:"Rows with no usage data",
  r_gerado_em:"Analysis run at",
  regua_padrao_aviso:"The base is too small to derive a threshold from it. In those cases CRAI used the default threshold, and says so rather than hiding it.",

  /* ── at-risk customer list ───────────────────────────────────── */
  buscar_cliente:"Search customer by code",
  busca_vazia:"No customer with that code",
  semdado_t:"{n} customers with no activity data",
  semdado_d:"Usage data was missing for these customers. CRAI does not assign risk to what it cannot measure, which is why they show a dash instead of a zero.",

  /* ── charge ──────────────────────────────────────────────────── */
  valor_invalido_t:"Invalid amount",
  valor_invalido_d:"Enter an amount such as 489.00.",

  /* ── recovery ────────────────────────────────────────────────── */
  caso_n:"Case {n}",
  f_tentativas:"Attempts already used",
  f_tentativas_de:"of the 3 allowed within the 7-day Pix Automático window",
  f_lido_de:"read by CRAI from this customer's history",
  f_nao_devolvido:"not returned by the API in this response",
  p2_sem_shap:"The API did not return the explanation for this decision.",
  p_racio_d:"The path the agent followed before deciding.",
  p_racio_vazio:"The API did not return the reasoning for this decision.",
  p3_sem_plano:"There is no retry to schedule: {decisao}.",
  melhor_eprofit:"highest return",
  canal_humano:"human channel",
  canal_nota:"The message goes out through {escolhido} because it is the only channel with a sending integration at this stage. The highest return in the comparison would be {melhor}.",
  p_canal_d:"Each channel has a cost and a chance of reply. CRAI compares the return of all of them before choosing.",
  p_canal_vazio:"The API did not return the channel comparison.",
  p5_d_api:"Sent through {canal}, without asking the customer to talk to anyone.",
  p5_sem_msg:"The API did not return a message for this case.",

  /* ── messages ────────────────────────────────────────────────── */
  msg_ninguem_t:"Nobody at risk in this base",
  msg_ninguem_d:"The analysis found no customer at high or critical risk. There is no message to prepare, and that is a result, not a failure.",
  origem_gerado:"text generated by the Claude API",
  origem_template:"text from a ready-made template",
  escolhida_bandit:"chosen",
  aceite_aprendido:"{p} learned acceptance",
  retorno_esperado:"expected return {v}",
  posterior_linha:"The {p} comes from the distribution CRAI keeps for this offer at this company: {a} acceptances against {b} refusals, total weight {peso}, market prior already included. Every real outcome moves this number.",
  decisao_resumo:"Chosen offer: {oferta}. Risk {risco}, monthly value {mrr}.",
  envio_simulado_t:"Simulated send",
  envio_registrado:"Cycle recorded under {id}.",
  envio_nao_registrado:"No cycle was recorded by this dispatch.",
  um_fora_do_lote:"This customer already went through the batch. Deciding again runs the batch once more.",
  um_explica:"Running the decision for this customer fires the whole batch, because the base thresholds need all of them to work.",
  decidir_um:"See this customer's decision",
  lote_de_novo:"Dispatch again",
  lote_tratados:"Customers handled",
  lote_tratados_pe:"{mrr} of monthly value involved",
  lote_pulados:"Customers skipped",
  lote_pulados_pe:"out of {n} received",
  lote_por_canal:"By channel",
  lote_lista_t:"The {n} customers handled",
  ver_decisao:"See decision",
  lote_ninguem_t:"Nobody was contacted in this batch",
  lote_ninguem_d:"No customer in this base met the e-Profit criterion. CRAI does not talk to people it is not worth contacting.",
  lote_pulados_t:"Why {n} were skipped",
  pulado_abaixo_do_criterio:"Below the return criterion",
  pulado_dado_insuficiente:"Not enough activity data",
  pulado_ciclo_aberto:"Already contacted, awaiting a reply",
  pulado_cadastro_invalido:"Invalid record in the spreadsheet",

  /* ── overview ────────────────────────────────────────────────── */
  vg_sem_taxa:"no dispatch yet",
  vg_sem_taxa_t:"The acceptance rate is still missing",
  vg_sem_taxa_d:"The projection needs the acceptance rate of the chosen offer, and that comes from the Messages tab. Dispatch a batch and the chart appears.",
  p_racio_t:"How the agent decided",
  p_canal_t:"How to reach the customer",
  ci_bot_whatsapp:"WhatsApp bot",
  ci_email_auto:"Automated email",
  ci_sms:"SMS",
  ci_ligacao_cs:"Support phone call",
  ci_pix_boleto_link:"Pix or bank slip link"
}
};

var idioma = "pt";
try{ var salvo = localStorage.getItem("crai_idioma"); if(salvo === "pt" || salvo === "en") idioma = salvo; }catch(e){}

function t(chave, p){
  var s = (T[idioma] && T[idioma][chave]) || (T.pt[chave]) || chave;
  if(p) for(var k in p) s = s.split("{" + k + "}").join(p[k]);
  return s;
}
